### ISSUE TITLE
Mary's project 2

### ISSUE THREAD

**Issue by marygriffus** [ga-dc/wdi9-project2-gallery#1]
Sorry, guys, this one is probably not for you!
My project is for collecting and presenting bra measurements and ratings, because they vary so much between brands that it can be really difficult to find something that fits well, let alone fits any other requirements (looking nice, being durable, any specialized functionality [strapless, etc]).

https://github.com/marygriffus/cups_of_data

**Comment by adambray** [comment]
👍 Planning folder looks good!
