### ISSUE TITLE
Wes Project 2 

### ISSUE THREAD

**Issue by wesareed** [ga-dc/wdi9-project2-gallery#15]
Link to repo: https://github.com/wesareed/bookstore
Link to deployed app: https://local-bookstore.herokuapp.com/

Link to youtube video: https://youtu.be/7SWwt-acaVU

Things you'd like specific feedback on:

Everything

**Comment by adambray** [comment]
Thanks for submitting... See my PR on your project for feedback.

**Comment by wesareed** [comment]
Thanks!
