### ISSUE TITLE
Josh's Project 2 

### ISSUE THREAD

**Issue by JoshNezi** [ga-dc/wdi9-project2-gallery#2]
Hello, 
I'm doing cheer ups for my second project. Cheerups is one of the suggested ideas. Cheerups are limited to 141 characters. Users will be able to promote Cheerups that they like and boost the reputation of the Cheerupper. 

https://github.com/JoshNezi/Cheerups.git

**Comment by tylercrosse** [comment]
Your current user stories are great, it might also be worthwhile to add some for full CRUD on comments.
