### ISSUE TITLE
Mike Project II: Twitter Scraper, the Reckoning, Part 1

### ISSUE THREAD

**Issue by MichaelNahum** [ga-dc/wdi9-project2-gallery#24]
Link to repo: https://github.com/MichaelNahum/TwitterScraper
Link to deployed app: https://miken-twitterscraper.herokuapp.com/

Screencast: https://youtu.be/BnyCI4YIlqs

Things you'd like specific feedback on: substituting tweets for tweet.attributes.

**Comment by adambray** [comment]
Hey Mike... please see my PR for feedback. I'm not sure what you meant by 

> substituting tweets for tweet.attributes

But I'm happy to go over that with you in person.
