### ISSUE TITLE
Martin's Project #2

### ISSUE THREAD

**Issue by 7ruth** [ga-dc/wdi9-project2-gallery#3]
https://github.com/7ruth/PadStats

**Comment by tylercrosse** [comment]
The way you have your user stories scoped you are essentially 100% invested in getting integration with google maps (or some geocoder & direction service) to work. That is potentially a big ask and doesn't give you much to fall back on if you can't get it to work. It might be worthwhile to spend a little time thinking about how you could pivot if you aren't able to get some of these features to work.
